/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_dj_GeoRelation_GeoRelation */

#ifndef _Included_com_dj_GeoRelation_GeoRelation
#define _Included_com_dj_GeoRelation_GeoRelation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dj_GeoRelation_GeoRelation
 * Method:    isPointOnLine
 * Signature: (Lcom/dj/Geomtery/Point;Lcom/dj/Geomtery/Line;)I
 */
JNIEXPORT jint JNICALL Java_com_dj_GeoRelation_GeoRelation_isPointOnLine
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_dj_GeoRelation_GeoRelation
 * Method:    LineLine
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dj_GeoRelation_GeoRelation_LineLine
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     com_dj_GeoRelation_GeoRelation
 * Method:    getStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dj_GeoRelation_GeoRelation_getStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_dj_GeoRelation_GeoRelation
 * Method:    getObject
 * Signature: (Lcom/dj/JNIDemo/Person;)Lcom/dj/JNIDemo/Person;
 */
JNIEXPORT jobject JNICALL Java_com_dj_GeoRelation_GeoRelation_getObject
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_dj_GeoRelation_GeoRelation
 * Method:    getPersonList
 * Signature: (Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_dj_GeoRelation_GeoRelation_getPersonList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_dj_GeoRelation_GeoRelation
 * Method:    passObject
 * Signature: (Lcom/dj/Geomtery/Point;)I
 */
JNIEXPORT jint JNICALL Java_com_dj_GeoRelation_GeoRelation_passObject
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
